name: flask-app
region: nyc

services:
  - name: web
    # Source configuration
    github:
      repo: your-username/your-flask-repo
      branch: main
      deploy_on_push: true
    
    # Build configuration
    build_command: pip install -r requirements.txt
    
    # Run configuration
    run_command: gunicorn --worker-tmp-dir /dev/shm app:app
    
    # Environment
    environment_slug: python
    
    # Instance configuration
    instance_count: 1
    instance_size_slug: basic-xxs
    
    # Health check
    health_check:
      http_path: /health
      initial_delay_seconds: 10
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    
    # HTTP configuration
    http_port: 8080
    
    # Environment variables
    envs:
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: FLASK_APP
      - value: "main.py" 